---
title: "生存分析的知识点"
author: "Purple Potato"
date: "2025-04-07"
output: html_document
---
# R包
```{r}
# 什么是R包？  --  

# 如何安装
install.packages("包的名字")
BiocManager::install("包的名字")

# 安装之后怎么办
library("包的名字")
```

# 变量
```{r}
# 什么是变量  --  变量就是人的名字

# 如何给变量起名字
x <- 123  # R语言更推崇此方式
y = "小六"  # 但是兼容这种方式
```

```{r}
# 变量有哪几种类型 -- 种类
x = 1  # 数值(初学可不区分double和integer)
y = c("A", 'B')  # 字符
z = c(T, F, FALSE, TRUE)  #布尔逻辑





# 变量有哪几种类型 -- 形状
x = c(1)
y = c(1, 2, 3)    # 他们仨是向量
z = 1:9

a = matrix(1:9, ncol = 3)  #他是矩阵

b = data.frame("第一列" = 1:3,  # 他是数据框
               "第二列" = c("A", "B", "C"),
               "第三列" = c(T, F, TRUE))

# 其他数据形状以后在介绍，在生信下游和临床流行病学中少见

# 变量之间的强制转换 -- 介绍最常用的
a = matrix(1:9, ncol = 3)
a_trans = as.data.frame(a)  # 将矩阵转变为数据框
a_double_trans = as.matrix(a_trans) # 将数据框转变为矩阵

b = 1:6
b_trans = as.data.frame(b)  # 将向量转变为数据框
b_double_trans = unlist(b_trans)  # 将数据库转变为向量
b_triple_trans = as.numeric(b_double_trans)
b_triple_trans_again = as.character(b_double_trans)
```

# 返回
```{r}
# 什么是返回  --  计算机给你的答复  --  需要你给计算机输入

# 返回自身
x = 1
x

# 返回数值计算结果
x = 1
y = 2
x - y

# 返回逻辑计算结果
x = 1
x > 1

# 返回可以作为参数参与计算  --  这个是R语言甚至很多编程的核心
x = 1:10
x > 5
table(x > 5) # table函数可以统计一个向量中各个取值共有几个
```


# 判断
```{r}
# 大小判断 -- 和数学逻辑一致
x = 1
y = 2
x > y
x < y
x == y  # 双重等号作为判定符
x >= y
x <= y
x != y  # R语言中!一般代表“不”

# 逻辑判断
x = T
y = F
x & y  # 与  注意，有时可以见到&&，新手可直接忽略其与&的差异
x | y  # 或
!x  # 非
```

# 数据框
```{r}
b = data.frame("first" = 1:3,
               "second" = c("A", "B", "C"),
               "third" = c(T, F, TRUE))

# 取第1列
b$first
b[,3]

# 取第2行
b[2,]
```

# 医学生最需要掌握的R语言技巧
```{r}
# 调包
# 1. 需要知道自己要做什么分析 -- 需要自己和导师设计
# 2. 需要知道自己这个分析需要靠什么R包实现
# 3. 需要能否模仿示例代码，结合自己数据修改代码
# 4. 需要能处理异常情况：报错 -- 需要自己不断摸索尝试，积累经验
```




















